"""
Django settings for ecommerce project.

Generated by 'django-admin startproject' using Django 3.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '55o&bxvfjb5dpl5)0k1cs-v-m#mx9l&*+*318*wucd_=byk48m'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [] # ["127.0.0.1"]


'''
DEFAULT_FROM_EMAIL = "miradotsangy@gmail.com"
SERVER_EMAIL = "miradotsangy@gmail.com"
EMAIL_HOST = "smtp.gmail.com" # '.sendgrid.net'
EMAIL_HOST_USER = "miradotsangy@gmail.com"
EMAIL_HOST_PASSWORD = "tsangy090197"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
'''
DEFAULT_FROM_EMAIL = "miradotsangy@gmail.com"

try:
    from .email_settings import host, user, password
    EMAIL_HOST = host # "smtp.gmail.com" # '.sendgrid.net'
    SERVER_EMAIL = user
    EMAIL_HOST_USER = user # "miradotsangy@gmail.com"
    EMAIL_HOST_PASSWORD = password # "password"
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
except: pass



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'products',
    'carts',
    'orders',
    'accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ecommerce.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # 'django.template.context_processors.media',
                # 'django.template.context_processors.static',
                # 'django.template.context_processors.i18n',
                # 'django.template.context_processors.tz',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecommerce.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'OPTIONS': {
            'sql_mode': 'traditional',
        },
        'NAME': 'py_ecommerce',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': '',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'fr'

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static/static_files'),
)

STATIC_ROOT = (
    os.path.join(BASE_DIR, 'static/static_root')
)

MEDIA_URL = "/media/"
MEDIA_ROOT = (
    os.path.join(BASE_DIR, "static/media")
)
# MEDIA_ROOT = os.path.join(os.path.dirname(BASE_DIR), 'static/media')
# Si le dossier static ets dans le dossier parent ( avec les bin - .idea - inclue - lib )

STRIPE_SECRET_KEY = "sk_test_JEUhCepQtUccNDR88gx8AKN000E8rhlnPg"
STRIPE_PUBLISHABLE_KEY = "pk_test_LzNRfadvfUZZi1l29eSbvKyF00Zovy3Bil"


'''
Après avoir indiquer les chemins des fichiers statci on fait  "python manage.py collectstatic"
Il faut installer angular pour ng & atom pour apm sur mon machin 
'''
INTERNAL_IPS = ['127.0.0.1']
