# Generated by Django 3.0.6 on 2020-07-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingmessage',
            name='message',
            field=models.CharField(max_length=250),
        ),
    ]
