# Generated by Django 3.0.6 on 2020-05-19 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_sale_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='sale_price',
        ),
    ]
