# Generated by Django 3.0.6 on 2020-05-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_products_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.FileField(null=True, upload_to='products/images/'),
        ),
        migrations.AddField(
            model_name='products',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True),
        ),
    ]
