# Generated by Django 3.0.6 on 2020-05-22 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_auto_20200522_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
