# Generated by Django 3.0.6 on 2020-05-22 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0008_auto_20200522_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='products',
            new_name='product',
        ),
    ]
