# Generated by Django 3.0.6 on 2020-05-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0013_auto_20200522_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
