# Generated by Django 3.0.6 on 2020-05-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200523_1045'),
        ('carts', '0015_cartitem_variaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='variaction',
            field=models.ManyToManyField(blank=True, to='products.Variation'),
        ),
    ]
