# Generated by Django 3.0.6 on 2020-05-23 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0016_auto_20200523_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='variaction',
            new_name='variactions',
        ),
    ]
