# Generated by Django 3.0.6 on 2020-05-23 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0017_auto_20200523_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='variactions',
            new_name='variations',
        ),
    ]
